ProjectScribe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400

handler404 = 'notes.views.custom_404_view'

urlpatterns = [
    path('@dmin/', admin.site.urls),
    path('', include('userApp.urls')),
    path('notes/',include('notes.urls')),
    path('todo/',include('toDo.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('all_notes/<str:userName>',views.notes,name="notes"),
    path('create/', views.create_note, name='create_note'),
    path('note_display/<int:note_id>/', views.note_display, name='note_display'),
    path('edit_note/<int:note_id>/', views.edit_note, name='editNote'),
    path('delete_note/<int:note_id>/', views.delete_note, name='deleteNote'),
    path('user/search/', views.user_note_search, name='userNoteSearch'),
    path('notesharestatus/<int:note_id>',views.note_share_status,name='noteShareStatus'),

    path('tutorials/<str:userName>/', views.tutorials, name='tutorials'),
    path('add_tutorial/<str:userName>/',views.add_tutorial,name='addTutorial'),
    path('edit_tutorial/<int:tuto_id>',views.edit_tutorial,name='editTutorial'),
    path('delete_tutorial/<int:tuto_id>',views.delete_tutorial,name='deleteTutorial'),
    path('search_tutorial/',views.user_search_tutorial,name='searchTutorial'),
    path('tutorial_sharestatus/<int:tuto_id>',views.tutorial_share_status,name='tutoShareStatus'),
    
]

toDo/urls.py
from django.urls import path
from . import views

app_name = "toDo"

urlpatterns = [
    path('add_task/<str:userName>',views.add_task, name='addTask'),
    path('edit_task/<int:task_id>',views.edit_task, name='editTask'),
    path('delete_task/<int:task_id>',views.delete_task, name='deleteTask'),
    path('alltasks/<str:userName>',views.all_tasks, name='allTasks'),
    path('prioritized_tasks/<str:userName>',views.prioritized_tasks,name='groupedTasks'),
    path('sort_tasks_asc/<str:userName>',views.sort_tasks_asc,name='sortTaskAsc'),
    path('sort_tasks_desc/<str:userName>',views.sort_tasks_desc,name='sortTaskDesc'),



]

userApp/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.decorators import login_required

app_name = "userApp"

urlpatterns=[
    path('',views.index,name='index'),
    path('index/login',views.index_login,name='indexLogin'),
    path('registration/',views.registration,name='registration'),
    path('google/redirect', login_required(views.google_redirect), name='google_redirect'),
    path('logout/',views.logout_user,name="logout"),
    path('shared_notes/',views.shared_notes, name="sharedNotes"),
    path('shared_tutorials/',views.shared_tutorials, name="sharedTutorials"),
    path('view_note/<int:note_id>/',views.view_note, name="viewNote"),
    path('shared_notes/<str:userName>/',views.user_shared_notes, name="userSharedNotes"),
    path('shared_tutorials/<str:userName>/',views.user_shared_tutorials, name="userSharedTutorials"),

]

notes/models.py
from django.db import models
from ckeditor.fields import RichTextField
from userApp.models import User
from django.utils import timezone


# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    created_at = models.DateField(default=timezone.now)
    noteowner = models.ForeignKey(User, on_delete=models.SET_NULL,null=True,default=None, related_name='allNote')
    is_shared = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    
class Tutorial(models.Model):
    title = models.CharField(max_length=200)
    short_descr = models.CharField(max_length=200,blank=True)
    link = models.URLField()
    tutorial_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='allTutorials')
    is_shared = models.BooleanField(default=False)
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title

toDo/models.py
import datetime
from django.db import models
from userApp.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator
# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=200)
    details = models.CharField(max_length=255,null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='allTasks')
    is_Active = models.BooleanField(default=True)
    created_at = models.DateField(default=timezone.now)
    due_date = models.DateField(null=False, default=None)
    priority = models.CharField(
        max_length=32,
        choices=[
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
        ],
    )

    def __str__(self):
        return self.title
    
    def remaining_days(self):
        if self.due_date:
            today = timezone.now().date()
            remaining_days = (self.due_date - today).days
            if remaining_days < 0:
                return "Overdue"
            else:
                return remaining_days
        else:
            return None

notes/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import *
from ckeditor.widgets import CKEditorWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class NoteForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=CKEditorWidget(attrs={'class': 'my-ckeditor-class',}))

    class Meta:
        model = Note
        fields = ['title', 'content', 'is_shared']

    def save(self, commit=True):
        # Get the current user
        user = self.instance.noteowner if self.instance.noteowner else self.initial.get('noteowner')
        if user is None:
            # If noteowner is not provided, use the currently logged-in user
            user = self.initial.get('user')
        
        # Create a new Note instance with the user as the note owner
        note = super().save(commit=False)
        note.noteowner = user

        if commit:
            note.save()

        return note

class TutorialForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit','Add Tutorial'))

    class Meta:
        model = Tutorial
        fields = ['title', 'short_descr', 'link', 'is_shared']

    def save(self, commit=True):
        # Get the current user
        user = self.instance.tutorial_owner if self.instance.tutorial_owner else self.initial.get('tutorial_owner')
        if user is None:
            # If tutorial_owner is not provided, use the currently logged-in user
            user = self.initial.get('user')
        
        # Create a new Note instance with the user as the note owner
        note = super().save(commit=False)
        note.tutorial_owner = user

        if commit:
            note.save()

        return note

toDo/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import *
from ckeditor.widgets import CKEditorWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.core.validators import MinValueValidator

class TaskForm(forms.ModelForm):
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit','Add Task'))


    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'min': timezone.now().date().isoformat()}),
        validators=[MinValueValidator(limit_value=timezone.now().date())]
            )
    
    class Meta:
        model = Task
        fields = ['title', 'details', 'is_Active', 'priority','due_date']

    # def save(self, commit=True):
    #     # Get the current user
    #     user = self.instance.owner if self.instance.owner else self.initial.get('owner')
    #     if user is None:
    #         # If noteowner is not provided, use the currently logged-in user
    #         user = self.initial.get('user')
        
    #     # Create a new Note instance with the user as the note owner
    #     task = super().save(commit=False)
    #     task.owner = user

    #     if commit:
    #         task.save()

    #     return task

notes/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Note, Tutorial
from userApp.models import User
from .forms import NoteForm,TutorialForm
import json
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


# Create your views here.
def notes(request, userName):
    current_user = request.user
    notes = Note.objects.filter(noteowner = current_user)
    return render(request, 'notes.html',{'notes': notes})


def note_display(request,note_id):
    try:
        note = Note.objects.get(id=note_id)
        data = {
            'id': note.pk,
            'title': note.title,
            'created_at':note.created_at,
            'content':note.content,
            'is_shared':note.is_shared,
        }
        return JsonResponse(data)
    except Note.DoesNotExist:
        return JsonResponse({'error': 'Object not found'}, status=404)


def create_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            form.instance.noteowner = request.user
            form.save()
            return redirect('notes:notes', userName=request.user.username)
    else:
        form = NoteForm()
    return render(request, 'createnote.html', {'form': form})

def edit_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    form = NoteForm(request.POST or None, instance=note)
    if form.is_valid():
        form.instance.noteowner = request.user
        form.save()
        return redirect('notes:notes', userName=request.user.username)

    return render(request, 'updatenote.html', {'form': form})

def delete_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    note.delete()
    return redirect('notes:notes', userName=request.user.username)


def note_share_status(request, note_id):
    note = get_object_or_404(Note,pk=note_id)
    if request.method == "POST":
        data = json.loads(request.body)
        is_shared = data['isShared']
        note.is_shared = is_shared
        note.save()
    # note = get_object_or_404(Note,pk=note_id)
    # is_shared = request.POST.get('isShared', False)
    # print(is_shared)
    # note.is_shared = is_shared
    # note.save()
    return JsonResponse({'message': 'Note shared status updated successfully'})


def user_note_search(request):
    if request.method == "POST":
        data = json.loads(request.body)
        search_keyword = data['search_keyword']
        current_user = request.user

    if search_keyword:
        filtered_notes = Note.objects.filter(noteowner=current_user).filter(title__icontains=search_keyword)
    else:
        filtered_notes = Note.objects.filter(noteowner=current_user)

    notes_data = []
    for note in filtered_notes:
        notes_data.append({'pk': note.pk, 'title': note.title})

    return JsonResponse(notes_data, safe=False)


def tutorials(request, userName):
    current_user = request.user
    tutorials = Tutorial.objects.filter(tutorial_owner =current_user).order_by('-created_at')
    paginator_t = Paginator(tutorials,10)
    page_no_t = request.GET.get('page')
    single_page_tutorials = paginator_t.get_page(page_no_t)
    form = TutorialForm()
    return render(request, 'tutorials.html', {'tutorials' :single_page_tutorials, 'form': form })


def add_tutorial(request, userName):
    if request.method == "POST":
        form = TutorialForm(request.POST)
        if form.is_valid():
            form.instance.tutorial_owner = request.user
            form.save()
    return redirect('notes:tutorials', userName=request.user)


def edit_tutorial(request, tuto_id):
    if request.method == 'GET':
        tuto = get_object_or_404(Tutorial, pk=tuto_id)
        form = TutorialForm(instance=tuto)
        form_data = {
                'title': form['title'].value(),
                'short_descr': form['short_descr'].value(),
                'link': form['link'].value(),
                'is_shared': form['is_shared'].value(),
            }
        return JsonResponse (form_data, safe=False)
    else:
        tuto = get_object_or_404(Tutorial, pk=tuto_id)
        form = TutorialForm(request.POST or None, instance = tuto)
        if form.is_valid():
            form.instance.tutorial_owner = request.user
            form.save()
            return redirect('notes:tutorials', userName=request.user.username)
        
def delete_tutorial(request, tuto_id):
    tuto = get_object_or_404(Tutorial, pk= tuto_id)
    tuto.delete()
    return redirect('notes:tutorials', userName=request.user.username)

def user_search_tutorial(request):
    current_user = request.user
    if request.method == "POST":
        search_keyword = request.POST.get('searchtuto','')

    if search_keyword:
        tutorials = Tutorial.objects.filter(tutorial_owner=current_user).filter(title__icontains=search_keyword)
        paginator_t = Paginator(tutorials,10)
        page_no_t = request.GET.get('page')
        single_page_tutorials = paginator_t.get_page(page_no_t)
    else:
        tutorials = Tutorial.objects.filter(tutorial_owner=current_user)

    form = TutorialForm()

    return render(request, 'tutorials.html', {'tutorials' :single_page_tutorials, 'form': form , 'search_keyword':search_keyword})

def tutorial_share_status(request, tuto_id):
    tuto = get_object_or_404(Tutorial, pk=tuto_id)
    if request.method == 'POST':
        data = json.loads(request.body)
        is_shared = data['isShared']
        tuto.is_shared = is_shared
        tuto.save()
    return JsonResponse({'message': 'Tutorial shared status updated successfully'})


def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

toDo/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from . models import Task
from .forms import TaskForm

# Create your views here.
def add_task(request,userName):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.instance.owner = request.user
            form.save()
    return redirect('toDo:allTasks', userName=request.user.username)


def edit_task(request,task_id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=task_id)
        form = TaskForm(instance=task)
        form_data = {
                'title': form['title'].value(),
                'details': form['details'].value(),
                'is_active': form['is_Active'].value(),
                'priority': form['priority'].value(),
                'due_date': form['due_date'].value(),
            }
        return JsonResponse (form_data, safe=False)
    else:
        task = get_object_or_404(Task, pk=task_id)
        form = TaskForm(request.POST or None, instance = task)
        if form.is_valid():
            form.instance.owner = request.user
            form.save()
            return redirect('toDo:allTasks', userName=request.user.username)


def delete_task(request,task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    return redirect('toDo:allTasks', userName=request.user.username)
    
    return HttpResponse('delete function')


def all_tasks(request,userName):
    current_user = request.user
    tasks = Task.objects.filter(owner=current_user)
    form = TaskForm()
    return render (request, 'todo.html', {'alltasks' : tasks,'form':form})

def prioritized_tasks(request,userName):
    current_user = request.user
    tasks = Task.objects.filter(owner=current_user).order_by('priority')
    grouped_tasks = {
        'high_priority' : [],
        'medium_priority' :[],
        'low_priority' : []
    }

    for task in tasks:
        if task.priority == 'high':
            grouped_tasks['high_priority'].append(task)
        elif task.priority == 'medium':
            grouped_tasks['medium_priority'].append(task)
        elif task.priority == 'low':
            grouped_tasks['low_priority'].append(task)
        form = TaskForm()

    return render(request, 'todo.html', {'grouped_tasks': grouped_tasks, 'form':form})


def sort_tasks_asc(request,userName):
    current_user = request.user
    tasks_ascending = Task.objects.filter(owner=current_user).order_by('due_date')
    form = TaskForm()
    return render (request, 'todo.html', {'alltasks' : tasks_ascending, 'form':form})

def sort_tasks_desc(request,userName):
    current_user = request.user
    tasks_descending = Task.objects.filter(owner=current_user).order_by('-due_date')
    form = TaskForm()
    return render (request, 'todo.html', {'alltasks' : tasks_descending, 'form':form})

def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

templates/add_edit_task.html
{% load crispy_forms_tags %}
    

    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Add new Task</h5>
        </div>
        <form method="POST" id="taskform" action="{% url 'toDo:addTask' request.user %}">
            {% csrf_token %}
            <div class="modal-body">
            {% crispy form %}
            </div>
        </form>
        <div class="modal-footer">
            <!--  button type="button" class="btn btn-primary" id="confirmDelete" data-object-id="popaddtaskbtn">Add</button>  -->
            <button type="button" class="btn btn-danger" data-dismiss="modal" id="popcanceltask">Close</button>
        </div>
        </div>
    </div>

templates/card_color.html
{% if task.priority == 'high' %} 
    custom-high-priority 
{% elif task.priority == 'medium' %} 
    custom-medium-priority 
{% elif task.priority == 'low' %} 
    custom-low-priority 
{% endif %}"

templates/index.html
{% extends 'indexbase.html' %}
{% load static %}
{% load socialaccount %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block extrahead %}
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}

{% block body %}
    <main>
        <div id="left-col" class="tm-section">
            <!-- Shared notes left -->
            <div class="tm-section-col tm-content">
                <div class="video-player">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/inUFWLESwhI?si=1usx-PE1equssu1O" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>
                <h3 class="tm-media-body">Shared Notes</h3>
                {% for note in notes %}
                <div class="tm-media">
                    <div class="tm-media-body">
                        <h5><a href="{% url 'userApp:viewNote' note.pk %}" class="tm-text-title">{{note.title}}</a></h5>
                        <div id="iframe-container">
                            <iframe id="iframe-content" frameborder="0" srcdoc="{{note.content}}" style="padding: 0;"></iframe>
                            <a id="iframe-href" href="{% url 'userApp:viewNote' note.pk %}"></a>
                        </div>
                        <div class="tm-text-secondary tm-media-span tm-text-small">
                            <span class="tm-text-left">Created By: {{ note.noteowner }}</span>
                            <span class="tm-text-right">{{ note.created_at }}</span>
                        </div>
                        <hr class="tm-hr tm-mr">
                    </div>
                </div>
                {% endfor %}

              <!-- paginator for shared noted -->  
              {% if notes.has_next %}
                <div class="tm-text-right">
                    <a href="?page_notes={{ notes.next_page_number }}" class="tm-btn tm-btn-next">Next</a>
                </div>
              {% endif %}
              {% if notes.has_previous %}
              <div class="tm-text-left">
                  <a href="?page_notes={{ notes.previous_page_number }}" class="tm-btn tm-btn-next">Previous</a>
              </div>
            {% endif %}
              <!-- paginator end --> 

            <!-- Shared notes End -->

            <!-- Shared tutorials left -->
            <h3 class="tm-media-body sh-tutorials">Shared Tutorials</h3>
                {% for tutorial in tutorials %}
                <div class="tm-media">
                    <div class="tm-media-body">
                        <h5><a href="#" class="tm-text-title">{{tutorial.title}}</a></h5>
                        <p class="tm-text-small tut-descr">{{tutorial.short_descr}}</p>
                        

                        {% comment %} <div id="iframe-container">
                            <iframe id="content-iframe" src="{{tutorial.link}}" frameborder="0"  style="padding: 0;"></iframe>
                        </div> {% endcomment %}

                        <div class="content-iframe">
                            <a href="{{tutorial.link}}">{{tutorial.link}}</a>
                        </div>

                        <div class="tm-text-secondary tm-media-span tm-text-small">
                            <span class="tm-text-left">Created By: {{ tutorial.tutorial_owner }}</span>
                            <span class="tm-text-right">{{ tutorial.created_at }}</span>
                        </div>
                
                        <hr class="tm-hr tm-mr">
                    </div>
                </div>
                {% endfor %}
                <!-- paginator for shared tutorials --> 
              {% if tutorials.has_next %}
                <div class="tm-text-right">
                    <a href="?page_tutorials={{ tutorials.next_page_number }}" class="tm-btn tm-btn-next">Next</a>
                </div>
              {% endif %}
              {% if tutorials.has_previous %}
              <div class="tm-text-left">
                  <a href="?page_tutorials={{ tutorials.previous_page_number }}" class="tm-btn tm-btn-next">Previous</a>
              </div>
            {% endif %}
              <!-- paginator end --> 
            <!-- Shared tutorials end -->
            </div>


            <!-- BG,Reigister right -->
            <div class="tm-section-col tm-parallax" data-parallax="scroll" data-image-src="{% static 'images/bg-03.jpg' %}">
            </div>
                <div class="registration-form">
                    <h2>Register</h2>
                    <form action="{% url 'userApp:registration'%}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" autofocus type="text" name="username" placeholder="Username" required>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="email" name="email" placeholder="Email Address" required>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" name="password" placeholder="Password" required>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password" required>
                        </div>
                        <input class="btn btn-primary form-control" type="submit" value="Register">
                    </form>

                    <a href="{% provider_login_url 'google' %}" class="google-button-a">
                    <button class="google-button">
                        <img class="button-icon" src="https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg" alt="Google Icon">
                        <span>Sign in with Google</span>
                    </button>
                    </a>
                    {% for message in messages %}
                        <div class="text-white"><small>{{ message }}</small></div>
                    {% endfor %}
                    Already have an account? <a href="{% url 'userApp:indexLogin' %}">Log In here.</a>
                </div>
        </div> <!-- BG,Reigister End -->
    </main>

    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/togglebar-index.js' %}"></script>
    <footer>
        {% block page_scripts %}
        {% endblock %}
    </footer> 
{% endblock %}

templates/indexnavbar.html
{% load static %}

<div class="nav-600">
    <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars"></i>
    </button>
    <a href="{% url 'userApp:index' %}"><li class="nav-item"><img src="{% static 'images/logo3.png' %}" id="logo-600"></li></a>
</div>

<div class="container">
    <nav class="tm-nav">        
        <ul id="tm-main-nav">
            <a href="{% url 'userApp:index' %}"><li class="nav-item"><img src="{% static 'images/logo3.png' %}" id="logo"></li></a>
            <li class="nav-item">
                <a href="{% url 'userApp:sharedNotes' %}" class="nav-link">
                    Shared Notes
                </a>
            </li>
            <li class="nav-item">
                <a href="{% url 'userApp:sharedTutorials' %}" class="nav-link">
                    Shared Tutorials
                </a>
            </li>
        </ul>
    </nav>
</div>

templates/sharednotes.html
{% extends 'indexbase.html' %}
{% load static %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/shared_note_tut.css' %}">
{% endblock %}

{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}


{% block body %}
<main>
    <div class="container">
        <h3 class="tm-media-body">Shared Notes</h3>
        <div class="form-section">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" placeholder="enter topic" class="form-control" name="searchnote" required>
                <input type="submit" value="Search" class="btn btn-primary">
                <a href="{% url 'userApp:sharedNotes'%}">View All</a>
                {% if search_keyword %}
                    <p>Showing results for '{{search_keyword}}'</p>
                {% endif %}
            </form>
        </div>
        <div class="row">
            {% if notes %}
            {% for note in notes %}
            <div class="col-lg-6">
                <div class="tm-media">
                    <div class="tm-media-body">
                        <h6><a href="{% url 'userApp:viewNote' note.pk %}" class="tm-text-title">{{note.title}}</a></h6>
                        <div id="iframe-container">
                            <iframe id="iframe-content" frameborder="0" srcdoc="{{note.content}}" style="padding: 0;"></iframe>
                            <a id="iframe-href" href="{% url 'userApp:viewNote' note.pk %}"></a>
                        </div>
                        <div class="tm-text-secondary tm-media-span tm-text-small">
                            <span class="tm-text-left">Created By: {{ note.noteowner }}</span>
                            <span class="tm-text-right">{{ note.created_at }}</span>
                        </div>
                        <hr class="tm-hr tm-mr">
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>0 results found for '{{search_keyword}}'</p>
            {% endif %}
        </div>



        <!-- paginator for shared noted -->  
        {% if notes.has_next %}
        <div class="tm-text-right">
            <a href="?page={{ notes.next_page_number }}" class="tm-btn tm-btn-next">Next</a>
        </div>
        {% endif %}
        {% if notes.has_previous %}
        <div class="tm-text-left">
            <a href="?page={{ notes.previous_page_number }}" class="tm-btn tm-btn-next">Previous</a>
        </div>
        {% endif %}
        <!-- paginator end --> 

    </div>

</main>

    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script src="{% static 'js/togglebar-index.js' %}"></script>
{% endblock %}

templates/usernavbar.html
{% load static %}
<div class="nav-600">
    <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars"></i>
    </button>
    <a href="{% url 'notes:notes' 'request.user.username' %}"><li class="nav-item"><img src="{% static 'images/logo3.png' %}" id="logo-600"></li></a>
</div>

<nav class="tm-nav">
    <ul id="tm-main-nav" style="margin: 0;" class="navitemsicons">
        {% url 'notes:notes' userName=request.user.username as notes %}
        {% url 'toDo:allTasks' userName=request.user.username as toDo %}
        {% url 'notes:tutorials' userName=request.user.username as tutorials %}
        {% url 'userApp:userSharedNotes' userName=request.user.username as userSharedNotes %}
        {% url 'userApp:userSharedTutorials' userName=request.user.username as userSharedTutorials %}

        <li class="nav-item"><a href="{% url 'notes:notes' request.user.username %}"><img src="{% static 'images/logo3.png' %}" id="logo"></a></li>
        <li class="nav-item">
            <a href="{{notes}}" class="nav-link">
                Notes
            </a>
        </li>
        <li class="nav-item">
            <a href="{{toDo}}" class="nav-link">
                ToDo Tasks
            </a>

        </li>
        <li class="nav-item">
            <a href="{{tutorials}}"  class="nav-link">
                Tutorials
            </a>
        </li>
        <li class="nav-item">
            <a href="{{userSharedNotes}}"  class="nav-link">
                Shared Notes
            </a>
        </li>
        <li class="nav-item">
            <a href="{{userSharedTutorials}}"  class="nav-link">
                Shared Tutorials
            </a>
        </li>
        <li class="nav-item nav-logout">
            <a href="{% url 'userApp:logout' %}" class="nav-logout">
                Logout <br> {{request.user.username}}
            </a>
        </li>
    </ul>
</nav>